//Authentication reducer
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED';
export const TOGGLE_SIGNOUT_MODAL = 'TOGGLE_SIGNOUT_MODAL';
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP';
export const TOGGLE_SHOW_PROFILE = 'TOGGLE_SHOW_PROFILE';
//User reducer
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SIGNOUT = 'UPDATE_USER_SIGNOUT';
export const UPDATE_USER_FOLLOWERS = 'UPDATE_USER_FOLLOWERS';
export const UPDATE_USER_FOLLOWINGS = 'UPDATE_USER_FOLLOWINGS';
//UserProfile reducer
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const NULL_USER_PROFILE = 'NULL_USER_PROFILE';





